cd /
md REDE
cd REDE
md ALAN-SOARES ANDREA-SANTOS BRUNO-OLIVEIRA CAMILA-LIRA CARLOS-SOUZA CAROLINE-NASCIMENTO DANIEL-SANTANA
md DARIO-FARIAS EDUARDO-RIOS FABIO-SILVA FELIPE-MACHADO FELIPE-BARRIOS FLAVIO-SOUZA FRANCISCO-CAVALCANTE
md GABRIEL-CREPALDI GABRIEL-LIMA GABRIEL-RODRIGUES GABRIELY-SILVA GUILHERME-ALVES GUSTAVO-TAVARES
md HENRIQUE-CABRAL ISAAC-SOUZA ISABELLY-MESQUITA JOAO-SOARES JONATHAN-FREITAS KAUA-MOTA
md LUCAS-SANTOS LUCAS-ANDRADE MATHEUS-CARVALHO NATALIA-MOREIRA NICOLAS-NASCIMENTO
md PALLOMA-SANTOS RAISSA-CARMO RAPHAELA-MELO REBECCA-GUEDES RIAM-ANDRE ROGERIO-JUNIOR
md SABRINA-BENEVIDES WALDANIA-OLIVEIRA
cls
dir