cd /
mkdir REDE
mkdir REDE
mkdir ALAN-SOARES ANDREA-SANTOS BRUNO-OLIVEIRA CAMILA-LIRA CARLOS-SOUZA CAROLINE-NASCIMENTO DANIEL-SANTANA
mkdir DARIO-FARIAS EDUARDO-RIOS FABIO-SILVA FELIPE-MACHADO FELIPE-BARRIOS FLAVIO-SOUZA FRANCISCO-CAVALCANTE
mkdir GABRIEL-CREPALDI GABRIEL-LIMA GABRIEL-RODRIGUES GABRIELY-SILVA GUILHERME-ALVES GUSTAVO-TAVARES
mkdir HENRIQUE-CABRAL ISAAC-SOUZA ISABELLY-MESQUITA JOAO-SOARES JONATHAN-FREITAS KAUA-MOTA
mkdir LUCAS-SANTOS LUCAS-ANDRADE MATHEUS-CARVALHO NATALIA-MOREIRA NICOLAS-NASCIMENTO
mkdir PALLOMA-SANTOS RAISSA-CARMO RAPHAELA-MELO REBECCA-GUEDES RIAM-ANDRE ROGERIO-JUNIOR
mkdir SABRINA-BENEVIDES WALDANIA-OLIVEIRA
clear
dir